from __future__ import annotations

import argparse
import hashlib
import html
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from . import __author__, __repository__, __version__
from .engine import scan_project
from .models import Finding
from .rules.catalog import RULES

SEVERITY_RANK = {"notice": 0, "warning": 1, "error": 2}
BASELINE_NAME = ".realitylint-baseline.json"


def score(findings: list[Finding]) -> int:
    penalties = {"error": 15, "warning": 6, "notice": 2}
    return max(0, 100 - sum(penalties.get(f.severity, 0) for f in findings))


def _summary(findings: list[Finding]) -> dict[str, int]:
    return {
        "errors": sum(f.severity == "error" for f in findings),
        "warnings": sum(f.severity == "warning" for f in findings),
        "notices": sum(f.severity == "notice" for f in findings),
    }


def _one_line(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ")


def render_text(findings: list[Finding]) -> str:
    counts = _summary(findings)
    lines = [f"RealityLint v{__version__} — by {__author__}", f"RealityLint score: {score(findings)}/100", ""]
    if not findings:
        lines.append("✓ No verifiable documentation drift found.")
    for f in findings:
        icon = {"error": "✗", "warning": "!", "notice": "·"}.get(f.severity, "·")
        lines.append(f"{icon} {_one_line(f.file)}:{f.line} {f.severity.upper()} {f.rule} {_one_line(f.message)}")
        if f.evidence:
            lines.append(f"  evidence: {_one_line(f.evidence)}")
        if f.suggestion:
            lines.append(f"  fix: {_one_line(f.suggestion)}")
    lines += ["", f"{counts['errors']} error(s), {counts['warnings']} warning(s), {counts['notices']} notice(s)."]
    return "\n".join(lines)


def _md_cell(value: str) -> str:
    value = value.replace("\r", " ").replace("\n", " ")
    value = html.escape(value, quote=False)
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("`", "\\`")


def render_markdown(findings: list[Finding]) -> str:
    counts = _summary(findings)
    lines = ["# RealityLint report", "", f"**Truth score: {score(findings)}/100**", ""]
    if not findings:
        lines.append("✅ No verifiable documentation drift found.")
        lines += ["", f"_Generated by RealityLint v{__version__} — by {__author__}_"]
        return "\n".join(lines)
    lines += ["| Severity | Rule | Location | Finding |", "|---|---|---|---|"]
    for f in findings:
        lines.append(f"| {_md_cell(f.severity)} | `{_md_cell(f.rule)}` | `{_md_cell(f.file)}:{f.line}` | {_md_cell(f.message)} |")
    lines += ["", f"Errors: **{counts['errors']}** · Warnings: **{counts['warnings']}** · Notices: **{counts['notices']}**", "", f"_Generated by RealityLint v{__version__} — by {__author__}_"]
    return "\n".join(lines)


def render_sarif(findings: list[Finding]) -> str:
    rules: dict[str, dict] = {}
    for f in findings:
        title, description = RULES.get(f.rule, (f.rule, f.rule))
        rules.setdefault(f.rule, {"id": f.rule, "shortDescription": {"text": title}, "fullDescription": {"text": description}})
    level = {"error": "error", "warning": "warning", "notice": "note"}
    payload = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {"name": "RealityLint", "version": __version__, "semanticVersion": __version__, "organization": __author__, "informationUri": __repository__, "rules": list(rules.values())}},
            "results": [{
                "ruleId": f.rule,
                "level": level.get(f.severity, "note"),
                "message": {"text": f.message},
                "locations": [{"physicalLocation": {"artifactLocation": {"uri": f.file.replace("\\", "/")}, "region": {"startLine": max(1, f.line)}}}],
            } for f in findings],
        }],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def render_junit(findings: list[Finding]) -> str:
    counts = _summary(findings)
    suite = ET.Element("testsuite", {
        "name": "RealityLint",
        "tests": str(max(1, len(findings))),
        "failures": str(counts["errors"]),
        "errors": "0",
        "skipped": "0",
    })
    if not findings:
        ET.SubElement(suite, "testcase", {"classname": "realitylint", "name": "documentation-consistency"})
    for finding in findings:
        case = ET.SubElement(suite, "testcase", {
            "classname": f"realitylint.{finding.rule}",
            "name": f"{finding.file}:{finding.line}",
        })
        if finding.severity == "error":
            node = ET.SubElement(case, "failure", {"type": finding.rule, "message": finding.message})
            node.text = finding.evidence or finding.suggestion or finding.message
        elif finding.severity == "warning":
            node = ET.SubElement(case, "system-out")
            node.text = f"WARNING {finding.rule}: {finding.message}"
        else:
            node = ET.SubElement(case, "system-out")
            node.text = f"NOTICE {finding.rule}: {finding.message}"
    return ET.tostring(suite, encoding="unicode")


def _gh_escape_data(value: str) -> str:
    return value.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def _gh_escape_property(value: str) -> str:
    return _gh_escape_data(value).replace(":", "%3A").replace(",", "%2C")


def github_annotations(findings: list[Finding]) -> list[str]:
    annotations: list[str] = []
    for f in findings:
        kind = "error" if f.severity == "error" else "warning" if f.severity == "warning" else "notice"
        annotations.append(
            f"::{kind} file={_gh_escape_property(f.file)},line={max(1, f.line)},title={_gh_escape_property(f.rule)}::"
            f"{_gh_escape_data(f.message)}"
        )
    return annotations


def _configure_utf8_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except (AttributeError, OSError, ValueError):
                pass


def _fingerprint(finding: Finding) -> str:
    payload = "\0".join((finding.rule, finding.file.replace("\\", "/"), finding.message))
    return hashlib.sha256(payload.encode("utf-8", errors="replace")).hexdigest()


def _write_baseline(path: Path, findings: list[Finding]) -> None:
    payload = {
        "version": 1,
        "generated_by": f"RealityLint {__version__}",
        "fingerprints": sorted({_fingerprint(finding) for finding in findings}),
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _apply_baseline(path: Path, findings: list[Finding]) -> list[Finding]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return findings
    fingerprints = data.get("fingerprints") if isinstance(data, dict) else None
    if not isinstance(fingerprints, list):
        return findings
    known = {str(value) for value in fingerprints}
    return [finding for finding in findings if _fingerprint(finding) not in known]


def _split_patterns(values: list[str] | None) -> list[str]:
    result: list[str] = []
    for value in values or []:
        result.extend(part.strip() for part in value.split(",") if part.strip())
    return result


def _print_rules() -> int:
    for rule, (title, _description) in sorted(RULES.items()):
        print(f"{rule}  {title}")
    return 0


def _explain_rule(rule: str) -> int:
    key = rule.upper()
    info = RULES.get(key)
    if info is None:
        print(f"Unknown RealityLint rule: {rule}", file=sys.stderr)
        return 2
    print(f"{key} — {info[0]}\n\n{info[1]}")
    return 0


def _init_project(root: Path) -> int:
    root = root.expanduser().resolve(strict=False)
    config_path = root / ".realitylint.toml"
    workflow_path = root / ".github/workflows/realitylint.yml"
    created: list[str] = []
    if not config_path.exists():
        config_path.write_text(
            '[realitylint]\n# docs = ["README*.md", "docs/**/*.md"]\n# exclude = ["docs/vendor/**"]\n\n[severity]\n# RL009 = "off"\n',
            encoding="utf-8",
        )
        created.append(".realitylint.toml")
    if not workflow_path.exists():
        workflow_path.parent.mkdir(parents=True, exist_ok=True)
        workflow_path.write_text(
            "name: RealityLint\n\non: [pull_request]\n\npermissions:\n  contents: read\n\njobs:\n  realitylint:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: voonterr/realitylint@v1\n        with:\n          all-docs: 'true'\n          fail-on: error\n",
            encoding="utf-8",
        )
        created.append(".github/workflows/realitylint.yml")
    print("Created: " + ", ".join(created) if created else "RealityLint is already initialized; no files changed.")
    return 0


def main(argv: list[str] | None = None) -> int:
    _configure_utf8_stdio()
    raw = list(sys.argv[1:] if argv is None else argv)
    if raw and raw[0] == "rules":
        return _print_rules()
    if raw and raw[0] == "explain":
        return _explain_rule(raw[1] if len(raw) > 1 else "")
    if raw and raw[0] == "init":
        return _init_project(Path(raw[1] if len(raw) > 1 else "."))

    parser = argparse.ArgumentParser(prog="realitylint", description="Detect deterministic documentation drift against repository facts.")
    parser.add_argument("root", nargs="?", default=".", help="Repository root (default: current directory)")
    parser.add_argument("--readme", default="README.md", help="Primary README path relative to root")
    parser.add_argument("--all-docs", action="store_true", help="Scan README*.md, docs/**/*.md and CONTRIBUTING.md")
    parser.add_argument("--docs", action="append", help="Additional comma-separated documentation glob(s); may be repeated")
    parser.add_argument("--config", help="Config path relative to root (default: .realitylint.toml)")
    parser.add_argument("--format", choices=["text", "json", "markdown", "sarif", "junit"], default="text")
    parser.add_argument("--fail-on", choices=["error", "warning", "never"], default="error")
    parser.add_argument("--github-annotations", action="store_true", help="Emit GitHub Actions workflow annotations")
    parser.add_argument("--baseline", help=f"Suppress findings stored in a baseline file (default: auto-use {BASELINE_NAME} if present)")
    parser.add_argument("--no-baseline", action="store_true", help="Do not auto-use .realitylint-baseline.json")
    parser.add_argument("--write-baseline", nargs="?", const=BASELINE_NAME, metavar="PATH", help="Write current findings as a baseline and exit successfully")
    parser.add_argument("--version", action="version", version=f"RealityLint {__version__} — by {__author__}")
    args = parser.parse_args(raw)

    root = Path(args.root)
    try:
        findings = scan_project(root, args.readme, all_docs=args.all_docs, patterns=_split_patterns(args.docs), config_path=args.config)
    except Exception as exc:
        print(f"RealityLint internal error: {exc.__class__.__name__}: {exc}", file=sys.stderr)
        return 2

    resolved_root = root.expanduser().resolve(strict=False)
    if args.write_baseline:
        baseline_path = Path(args.write_baseline)
        if not baseline_path.is_absolute():
            baseline_path = resolved_root / baseline_path
        try:
            _write_baseline(baseline_path, findings)
        except OSError as exc:
            print(f"RealityLint: could not write baseline: {exc}", file=sys.stderr)
            return 2
        print(f"Wrote RealityLint baseline with {len(findings)} finding(s): {baseline_path}")
        return 0

    baseline_path: Path | None = None
    if args.baseline:
        baseline_path = Path(args.baseline)
        if not baseline_path.is_absolute():
            baseline_path = resolved_root / baseline_path
    elif not args.no_baseline:
        auto = resolved_root / BASELINE_NAME
        if auto.is_file():
            baseline_path = auto
    if baseline_path is not None:
        findings = _apply_baseline(baseline_path, findings)

    if args.github_annotations:
        for line in github_annotations(findings):
            print(line)

    if args.format == "text":
        output = render_text(findings)
    elif args.format == "markdown":
        output = render_markdown(findings)
    elif args.format == "sarif":
        output = render_sarif(findings)
    elif args.format == "junit":
        output = render_junit(findings)
    else:
        output = json.dumps({"tool": {"name": "RealityLint", "version": __version__, "author": __author__, "repository": __repository__}, "score": score(findings), "summary": _summary(findings), "findings": [f.to_dict() for f in findings]}, indent=2, ensure_ascii=False)
    print(output)

    if args.fail_on == "never":
        return 0
    threshold = SEVERITY_RANK[args.fail_on]
    return 1 if any(SEVERITY_RANK.get(f.severity, 0) >= threshold for f in findings) else 0


if __name__ == "__main__":
    sys.exit(main())
