from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

from . import __author__, __repository__, __version__
from .models import Finding
from .scanner import scan

SEVERITY_RANK = {"notice": 0, "warning": 1, "error": 2}


def score(findings: list[Finding]) -> int:
    penalties = {"error": 15, "warning": 6, "notice": 2}
    return max(0, 100 - sum(penalties.get(f.severity, 0) for f in findings))


def _summary(findings: list[Finding]) -> dict[str, int]:
    return {
        "errors": sum(f.severity == "error" for f in findings),
        "warnings": sum(f.severity == "warning" for f in findings),
        "notices": sum(f.severity == "notice" for f in findings),
    }


def _one_line(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ")


def render_text(findings: list[Finding]) -> str:
    counts = _summary(findings)
    lines = [f"RealityLint v{__version__} — by {__author__}", f"RealityLint score: {score(findings)}/100", ""]
    if not findings:
        lines.append("✓ No verifiable README drift found.")
    for f in findings:
        icon = {"error": "✗", "warning": "!", "notice": "·"}.get(f.severity, "·")
        lines.append(f"{icon} {_one_line(f.file)}:{f.line} {f.severity.upper()} {f.rule} {_one_line(f.message)}")
        if f.evidence:
            lines.append(f"  evidence: {_one_line(f.evidence)}")
        if f.suggestion:
            lines.append(f"  fix: {_one_line(f.suggestion)}")
    lines += ["", f"{counts['errors']} error(s), {counts['warnings']} warning(s), {counts['notices']} notice(s)."]
    return "\n".join(lines)


def _md_cell(value: str) -> str:
    value = value.replace("\r", " ").replace("\n", " ")
    value = html.escape(value, quote=False)
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("`", "\\`")


def render_markdown(findings: list[Finding]) -> str:
    counts = _summary(findings)
    lines = ["# RealityLint report", "", f"**Truth score: {score(findings)}/100**", ""]
    if not findings:
        lines.append("✅ No verifiable README drift found.")
        lines += ["", f"_Generated by RealityLint v{__version__} — by {__author__}_"]
        return "\n".join(lines)
    lines += ["| Severity | Rule | Location | Finding |", "|---|---|---|---|"]
    for f in findings:
        lines.append(f"| {_md_cell(f.severity)} | `{_md_cell(f.rule)}` | `{_md_cell(f.file)}:{f.line}` | {_md_cell(f.message)} |")
    lines += ["", f"Errors: **{counts['errors']}** · Warnings: **{counts['warnings']}** · Notices: **{counts['notices']}**", "", f"_Generated by RealityLint v{__version__} — by {__author__}_"]
    return "\n".join(lines)


def render_sarif(findings: list[Finding]) -> str:
    rules: dict[str, dict] = {}
    for f in findings:
        rules.setdefault(f.rule, {"id": f.rule, "shortDescription": {"text": f.rule}})
    level = {"error": "error", "warning": "warning", "notice": "note"}
    payload = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {"name": "RealityLint", "version": __version__, "semanticVersion": __version__, "organization": __author__, "informationUri": __repository__, "rules": list(rules.values())}},
            "results": [{
                "ruleId": f.rule,
                "level": level.get(f.severity, "note"),
                "message": {"text": f.message},
                "locations": [{"physicalLocation": {"artifactLocation": {"uri": f.file.replace("\\", "/")}, "region": {"startLine": max(1, f.line)}}}],
            } for f in findings],
        }],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def _gh_escape_data(value: str) -> str:
    return value.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def _gh_escape_property(value: str) -> str:
    return _gh_escape_data(value).replace(":", "%3A").replace(",", "%2C")


def github_annotations(findings: list[Finding]) -> list[str]:
    annotations: list[str] = []
    for f in findings:
        kind = "error" if f.severity == "error" else "warning" if f.severity == "warning" else "notice"
        annotations.append(
            f"::{kind} file={_gh_escape_property(f.file)},line={max(1, f.line)},title={_gh_escape_property(f.rule)}::"
            f"{_gh_escape_data(f.message)}"
        )
    return annotations


def _configure_utf8_stdio() -> None:
    """Prefer UTF-8 for human-readable CLI output on legacy Windows consoles/CI."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except (AttributeError, OSError, ValueError):
                pass


def main(argv: list[str] | None = None) -> int:
    _configure_utf8_stdio()
    parser = argparse.ArgumentParser(prog="realitylint", description="Verify README claims against repository facts.")
    parser.add_argument("root", nargs="?", default=".", help="Repository root (default: current directory)")
    parser.add_argument("--readme", default="README.md", help="README path relative to root")
    parser.add_argument("--format", choices=["text", "json", "markdown", "sarif"], default="text")
    parser.add_argument("--fail-on", choices=["error", "warning", "never"], default="error")
    parser.add_argument("--github-annotations", action="store_true", help="Emit GitHub Actions workflow annotations")
    parser.add_argument("--version", action="version", version=f"RealityLint {__version__} — by {__author__}")
    args = parser.parse_args(argv)

    try:
        findings = scan(Path(args.root), args.readme)
    except Exception as exc:  # Last-resort CLI boundary: malformed repos should not produce a traceback.
        print(f"RealityLint internal error: {exc.__class__.__name__}: {exc}", file=sys.stderr)
        return 2

    if args.github_annotations:
        for line in github_annotations(findings):
            print(line)

    if args.format == "text":
        output = render_text(findings)
    elif args.format == "markdown":
        output = render_markdown(findings)
    elif args.format == "sarif":
        output = render_sarif(findings)
    else:
        output = json.dumps({"tool": {"name": "RealityLint", "version": __version__, "author": __author__, "repository": __repository__}, "score": score(findings), "summary": _summary(findings), "findings": [f.to_dict() for f in findings]}, indent=2, ensure_ascii=False)
    print(output)

    if args.fail_on == "never":
        return 0
    threshold = SEVERITY_RANK[args.fail_on]
    return 1 if any(SEVERITY_RANK.get(f.severity, 0) >= threshold for f in findings) else 0


if __name__ == "__main__":
    sys.exit(main())
